"""Ampliación del catálogo: los 195 países (193 de la ONU + Santa Sede + Palestina) con sus
aeropuertos principales. Formato: (código IATA de ciudad/aeropuerto, ciudad, país, ISO, región, lat, lon).
Coordenadas aproximadas (solo se usan para distancias y el mapa).
"""

EXTRA = [
    # ---------------- Europa ----------------
    ("CTA", "Catania (Sicilia)", "Italia", "IT", "EU", 37.47, 15.07),
    ("BLQ", "Bolonia", "Italia", "IT", "EU", 44.53, 11.29),
    ("CAG", "Cagliari (Cerdeña)", "Italia", "IT", "EU", 39.25, 9.05),
    ("OLB", "Olbia (Cerdeña)", "Italia", "IT", "EU", 40.90, 9.52),
    ("BRI", "Bari", "Italia", "IT", "EU", 41.14, 16.76),
    ("MRS", "Marsella", "Francia", "FR", "EU", 43.44, 5.22),
    ("BOD", "Burdeos", "Francia", "FR", "EU", 44.83, -0.72),
    ("TLS", "Toulouse", "Francia", "FR", "EU", 43.63, 1.37),
    ("DUS", "Düsseldorf", "Alemania", "DE", "EU", 51.29, 6.77),
    ("CGN", "Colonia", "Alemania", "DE", "EU", 50.87, 7.14),
    ("STR", "Stuttgart", "Alemania", "DE", "EU", 48.69, 9.22),
    ("GDN", "Gdansk", "Polonia", "PL", "EU", 54.38, 18.47),
    ("SKG", "Salónica", "Grecia", "GR", "EU", 40.52, 22.97),
    ("CFU", "Corfú", "Grecia", "GR", "EU", 39.60, 19.91),
    ("RHO", "Rodas", "Grecia", "GR", "EU", 36.41, 28.09),
    ("PFO", "Pafos", "Chipre", "CY", "EU", 34.72, 32.49),
    ("ADB", "Esmirna", "Turquía", "TR", "EU", 38.29, 27.16),
    ("DLM", "Dalaman", "Turquía", "TR", "EU", 36.71, 28.79),
    ("BJV", "Bodrum", "Turquía", "TR", "EU", 37.25, 27.66),
    ("ZAG", "Zagreb", "Croacia", "HR", "EU", 45.74, 16.07),
    ("BGO", "Bergen", "Noruega", "NO", "EU", 60.29, 5.22),
    ("LUX", "Luxemburgo", "Luxemburgo", "LU", "EU", 49.63, 6.21),
    ("BTS", "Bratislava", "Eslovaquia", "SK", "EU", 48.17, 17.21),
    ("LJU", "Liubliana", "Eslovenia", "SI", "EU", 46.22, 14.46),
    ("BEG", "Belgrado", "Serbia", "RS", "EU", 44.82, 20.29),
    ("SJJ", "Sarajevo", "Bosnia y Herzegovina", "BA", "EU", 43.82, 18.33),
    ("TGD", "Podgorica", "Montenegro", "ME", "EU", 42.36, 19.25),
    ("TIV", "Tivat", "Montenegro", "ME", "EU", 42.40, 18.72),
    ("SKP", "Skopie", "Macedonia del Norte", "MK", "EU", 41.96, 21.62),
    ("PRN", "Pristina", "Kosovo", "XK", "EU", 42.57, 21.04),
    ("KIV", "Chisináu", "Moldavia", "MD", "EU", 46.93, 28.93),
    ("IEV", "Kiev", "Ucrania", "UA", "EU", 50.35, 30.89),
    ("MSQ", "Minsk", "Bielorrusia", "BY", "EU", 53.88, 28.03),
    ("MOW", "Moscú", "Rusia", "RU", "EU", 55.75, 37.62),
    ("LED", "San Petersburgo", "Rusia", "RU", "EU", 59.80, 30.26),
    ("TBS", "Tiflis", "Georgia", "GE", "EU", 41.67, 44.95),
    ("EVN", "Ereván", "Armenia", "AM", "EU", 40.15, 44.40),
    ("BAK", "Bakú", "Azerbaiyán", "AZ", "EU", 40.47, 50.05),
    # ---------------- Oriente Medio ----------------
    ("RUH", "Riad", "Arabia Saudí", "SA", "ME", 24.96, 46.70),
    ("JED", "Yeda", "Arabia Saudí", "SA", "ME", 21.68, 39.16),
    ("KWI", "Kuwait", "Kuwait", "KW", "ME", 29.24, 47.97),
    ("BAH", "Baréin", "Baréin", "BH", "ME", 26.27, 50.63),
    ("BEY", "Beirut", "Líbano", "LB", "ME", 33.82, 35.49),
    ("BGW", "Bagdad", "Irak", "IQ", "ME", 33.26, 44.23),
    ("EBL", "Erbil", "Irak", "IQ", "ME", 36.24, 43.96),
    ("THR", "Teherán", "Irán", "IR", "ME", 35.42, 51.15),
    ("DAM", "Damasco", "Siria", "SY", "ME", 33.41, 36.52),
    ("SAH", "Saná", "Yemen", "YE", "ME", 15.48, 44.22),
    # ---------------- África ----------------
    ("ALG", "Argel", "Argelia", "DZ", "AF", 36.69, 3.22),
    ("TIP", "Trípoli", "Libia", "LY", "AF", 32.66, 13.16),
    ("AGA", "Agadir", "Marruecos", "MA", "AF", 30.33, -9.41),
    ("FEZ", "Fez", "Marruecos", "MA", "AF", 33.93, -4.98),
    ("SSH", "Sharm el-Sheij", "Egipto", "EG", "AF", 27.98, 34.39),
    ("LXR", "Lúxor", "Egipto", "EG", "AF", 25.67, 32.71),
    ("DJE", "Yerba", "Túnez", "TN", "AF", 33.87, 10.78),
    ("NKC", "Nuakchot", "Mauritania", "MR", "AF", 18.10, -15.95),
    ("BKO", "Bamako", "Malí", "ML", "AF", 12.53, -7.95),
    ("NIM", "Niamey", "Níger", "NE", "AF", 13.48, 2.18),
    ("NDJ", "Yamena", "Chad", "TD", "AF", 12.13, 15.03),
    ("KRT", "Jartum", "Sudán", "SD", "AF", 15.59, 32.55),
    ("JUB", "Yuba", "Sudán del Sur", "SS", "AF", 4.87, 31.60),
    ("ASM", "Asmara", "Eritrea", "ER", "AF", 15.29, 38.91),
    ("ADD", "Adís Abeba", "Etiopía", "ET", "AF", 8.98, 38.80),
    ("JIB", "Yibuti", "Yibuti", "DJ", "AF", 11.55, 43.16),
    ("MGQ", "Mogadiscio", "Somalia", "SO", "AF", 2.01, 45.30),
    ("MBA", "Mombasa", "Kenia", "KE", "AF", -4.03, 39.59),
    ("JRO", "Kilimanjaro", "Tanzania", "TZ", "AF", -3.43, 37.07),
    ("DAR", "Dar es-Salam", "Tanzania", "TZ", "AF", -6.88, 39.20),
    ("EBB", "Entebbe (Kampala)", "Uganda", "UG", "AF", 0.04, 32.44),
    ("KGL", "Kigali", "Ruanda", "RW", "AF", -1.97, 30.14),
    ("BJM", "Buyumbura", "Burundi", "BI", "AF", -3.32, 29.32),
    ("FIH", "Kinsasa", "R. D. del Congo", "CD", "AF", -4.39, 15.44),
    ("BZV", "Brazzaville", "Congo", "CG", "AF", -4.25, 15.25),
    ("LBV", "Libreville", "Gabón", "GA", "AF", 0.46, 9.41),
    ("SSG", "Malabo", "Guinea Ecuatorial", "GQ", "AF", 3.76, 8.71),
    ("DLA", "Duala", "Camerún", "CM", "AF", 4.01, 9.72),
    ("BGF", "Bangui", "Rep. Centroafricana", "CF", "AF", 4.40, 18.52),
    ("LOS", "Lagos", "Nigeria", "NG", "AF", 6.58, 3.32),
    ("ABV", "Abuya", "Nigeria", "NG", "AF", 9.01, 7.26),
    ("COO", "Cotonú", "Benín", "BJ", "AF", 6.36, 2.38),
    ("LFW", "Lomé", "Togo", "TG", "AF", 6.17, 1.25),
    ("ACC", "Acra", "Ghana", "GH", "AF", 5.61, -0.17),
    ("ABJ", "Abiyán", "Costa de Marfil", "CI", "AF", 5.26, -3.93),
    ("OUA", "Uagadugú", "Burkina Faso", "BF", "AF", 12.35, -1.51),
    ("ROB", "Monrovia", "Liberia", "LR", "AF", 6.23, -10.36),
    ("FNA", "Freetown", "Sierra Leona", "SL", "AF", 8.62, -13.20),
    ("CKY", "Conakri", "Guinea", "GN", "AF", 9.58, -13.61),
    ("OXB", "Bisáu", "Guinea-Bisáu", "GW", "AF", 11.89, -15.65),
    ("BJL", "Banjul", "Gambia", "GM", "AF", 13.34, -16.65),
    ("RAI", "Praia", "Cabo Verde", "CV", "AF", 14.92, -23.49),
    ("BVC", "Boa Vista", "Cabo Verde", "CV", "AF", 16.14, -22.89),
    ("TMS", "Santo Tomé", "Santo Tomé y Príncipe", "ST", "AF", 0.38, 6.71),
    ("LAD", "Luanda", "Angola", "AO", "AF", -8.86, 13.23),
    ("WDH", "Windhoek", "Namibia", "NA", "AF", -22.48, 17.47),
    ("GBE", "Gaborone", "Botsuana", "BW", "AF", -24.56, 25.92),
    ("HRE", "Harare", "Zimbabue", "ZW", "AF", -17.93, 31.09),
    ("VFA", "Cataratas Victoria", "Zimbabue", "ZW", "AF", -18.10, 25.84),
    ("LUN", "Lusaka", "Zambia", "ZM", "AF", -15.33, 28.45),
    ("LLW", "Lilongüe", "Malaui", "MW", "AF", -13.79, 33.78),
    ("MPM", "Maputo", "Mozambique", "MZ", "AF", -25.92, 32.57),
    ("TNR", "Antananarivo", "Madagascar", "MG", "AF", -18.80, 47.48),
    ("NOS", "Nosy Be", "Madagascar", "MG", "AF", -13.31, 48.31),
    ("HAH", "Moroni", "Comoras", "KM", "AF", -11.53, 43.27),
    ("SEZ", "Mahé", "Seychelles", "SC", "AF", -4.67, 55.52),
    ("MSU", "Maseru", "Lesoto", "LS", "AF", -29.46, 27.55),
    ("SHO", "Manzini", "Esuatini", "SZ", "AF", -26.36, 31.72),
    ("DUR", "Durban", "Sudáfrica", "ZA", "AF", -29.61, 31.12),
    ("RUN", "Reunión", "Francia (Reunión)", "RE", "AF", -20.89, 55.51),
    # ---------------- Asia ----------------
    ("KHI", "Karachi", "Pakistán", "PK", "AS", 24.91, 67.16),
    ("ISB", "Islamabad", "Pakistán", "PK", "AS", 33.56, 72.85),
    ("LHE", "Lahore", "Pakistán", "PK", "AS", 31.52, 74.40),
    ("DAC", "Daca", "Bangladés", "BD", "AS", 23.84, 90.40),
    ("PBH", "Paro", "Bután", "BT", "AS", 27.40, 89.42),
    ("RGN", "Rangún", "Myanmar", "MM", "AS", 16.91, 96.13),
    ("VTE", "Vientián", "Laos", "LA", "AS", 17.99, 102.56),
    ("LPQ", "Luang Prabang", "Laos", "LA", "AS", 19.90, 102.16),
    ("PNH", "Nom Pen", "Camboya", "KH", "AS", 11.55, 104.84),
    ("REP", "Siem Reap (Angkor)", "Camboya", "KH", "AS", 13.41, 103.81),
    ("BWN", "Bandar Seri Begawan", "Brunéi", "BN", "AS", 4.94, 114.93),
    ("DIL", "Dili", "Timor Oriental", "TL", "AS", -8.55, 125.52),
    ("ULN", "Ulán Bator", "Mongolia", "MN", "AS", 47.65, 106.82),
    ("FNJ", "Pionyang", "Corea del Norte", "KP", "AS", 39.22, 125.67),
    ("KBL", "Kabul", "Afganistán", "AF", "AS", 34.57, 69.21),
    ("ALA", "Almaty", "Kazajistán", "KZ", "AS", 43.35, 77.04),
    ("NQZ", "Astaná", "Kazajistán", "KZ", "AS", 51.02, 71.47),
    ("TAS", "Taskent", "Uzbekistán", "UZ", "AS", 41.26, 69.28),
    ("SKD", "Samarcanda", "Uzbekistán", "UZ", "AS", 39.70, 66.98),
    ("FRU", "Biskek", "Kirguistán", "KG", "AS", 43.06, 74.48),
    ("DYU", "Dusambé", "Tayikistán", "TJ", "AS", 38.54, 68.83),
    ("ASB", "Asjabad", "Turkmenistán", "TM", "AS", 37.99, 58.36),
    ("CAN", "Cantón", "China", "CN", "AS", 23.39, 113.30),
    ("SZX", "Shenzhen", "China", "CN", "AS", 22.64, 113.81),
    ("CTU", "Chengdu", "China", "CN", "AS", 30.58, 103.95),
    ("XIY", "Xi'an", "China", "CN", "AS", 34.45, 108.75),
    ("MFM", "Macao", "China", "MO", "AS", 22.15, 113.59),
    ("FUK", "Fukuoka", "Japón", "JP", "AS", 33.59, 130.45),
    ("OKA", "Okinawa", "Japón", "JP", "AS", 26.20, 127.65),
    ("SPK", "Sapporo", "Japón", "JP", "AS", 42.78, 141.69),
    ("PUS", "Busan", "Corea del Sur", "KR", "AS", 35.18, 128.94),
    ("CJU", "Jeju", "Corea del Sur", "KR", "AS", 33.51, 126.49),
    ("BLR", "Bangalore", "India", "IN", "AS", 13.20, 77.71),
    ("MAA", "Chennai", "India", "IN", "AS", 12.99, 80.17),
    ("GOI", "Goa", "India", "IN", "AS", 15.38, 73.83),
    ("CCU", "Calcuta", "India", "IN", "AS", 22.65, 88.45),
    ("COK", "Kochi (Kerala)", "India", "IN", "AS", 10.15, 76.40),
    ("JAI", "Jaipur", "India", "IN", "AS", 26.82, 75.81),
    ("LOP", "Lombok", "Indonesia", "ID", "AS", -8.76, 116.28),
    ("CNX", "Chiang Mai", "Tailandia", "TH", "AS", 18.77, 98.96),
    ("USM", "Koh Samui", "Tailandia", "TH", "AS", 9.55, 100.06),
    ("KBV", "Krabi", "Tailandia", "TH", "AS", 8.10, 98.99),
    ("DAD", "Da Nang", "Vietnam", "VN", "AS", 16.04, 108.20),
    ("PQC", "Phu Quoc", "Vietnam", "VN", "AS", 10.17, 103.99),
    ("CEB", "Cebú", "Filipinas", "PH", "AS", 10.31, 123.98),
    ("MPH", "Boracay (Caticlan)", "Filipinas", "PH", "AS", 11.92, 121.95),
    ("PEN", "Penang", "Malasia", "MY", "AS", 5.30, 100.28),
    ("BKI", "Kota Kinabalu (Borneo)", "Malasia", "MY", "AS", 5.94, 116.05),
    ("LGK", "Langkawi", "Malasia", "MY", "AS", 6.33, 99.73),
    # ---------------- Oceanía ----------------
    ("BNE", "Brisbane", "Australia", "AU", "OC", -27.38, 153.12),
    ("PER", "Perth", "Australia", "AU", "OC", -31.94, 115.97),
    ("CNS", "Cairns", "Australia", "AU", "OC", -16.88, 145.75),
    ("ADL", "Adelaida", "Australia", "AU", "OC", -34.94, 138.53),
    ("CHC", "Christchurch", "Nueva Zelanda", "NZ", "OC", -43.49, 172.53),
    ("ZQN", "Queenstown", "Nueva Zelanda", "NZ", "OC", -45.02, 168.74),
    ("NAN", "Nadi", "Fiyi", "FJ", "OC", -17.76, 177.44),
    ("POM", "Port Moresby", "Papúa Nueva Guinea", "PG", "OC", -9.44, 147.22),
    ("HIR", "Honiara", "Islas Salomón", "SB", "OC", -9.43, 160.05),
    ("VLI", "Port Vila", "Vanuatu", "VU", "OC", -17.70, 168.32),
    ("APW", "Apia", "Samoa", "WS", "OC", -13.83, -172.01),
    ("TBU", "Nukualofa", "Tonga", "TO", "OC", -21.24, -175.15),
    ("TRW", "Tarawa", "Kiribati", "KI", "OC", 1.38, 173.15),
    ("FUN", "Funafuti", "Tuvalu", "TV", "OC", -8.52, 179.20),
    ("INU", "Nauru", "Nauru", "NR", "OC", -0.55, 166.92),
    ("MAJ", "Majuro", "Islas Marshall", "MH", "OC", 7.06, 171.27),
    ("PNI", "Pohnpei", "Micronesia", "FM", "OC", 6.99, 158.21),
    ("ROR", "Koror", "Palaos", "PW", "OC", 7.37, 134.54),
    ("NOU", "Numea", "Francia (Nueva Caledonia)", "NC", "OC", -22.01, 166.21),
    ("GUM", "Guam", "Estados Unidos (Guam)", "GU", "OC", 13.48, 144.80),
    # ---------------- Norteamérica ----------------
    ("SEA", "Seattle", "Estados Unidos", "US", "NA", 47.45, -122.31),
    ("DFW", "Dallas", "Estados Unidos", "US", "NA", 32.90, -97.04),
    ("ATL", "Atlanta", "Estados Unidos", "US", "NA", 33.64, -84.43),
    ("DEN", "Denver", "Estados Unidos", "US", "NA", 39.86, -104.67),
    ("HOU", "Houston", "Estados Unidos", "US", "NA", 29.98, -95.34),
    ("PHL", "Filadelfia", "Estados Unidos", "US", "NA", 39.87, -75.24),
    ("PHX", "Phoenix", "Estados Unidos", "US", "NA", 33.43, -112.01),
    ("SAN", "San Diego", "Estados Unidos", "US", "NA", 32.73, -117.19),
    ("MSY", "Nueva Orleans", "Estados Unidos", "US", "NA", 29.99, -90.26),
    ("BNA", "Nashville", "Estados Unidos", "US", "NA", 36.12, -86.68),
    ("YYC", "Calgary", "Canadá", "CA", "NA", 51.13, -114.01),
    ("YOW", "Ottawa", "Canadá", "CA", "NA", 45.32, -75.67),
    ("YQB", "Quebec", "Canadá", "CA", "NA", 46.79, -71.39),
    # ---------------- Latinoamérica y Caribe ----------------
    ("GDL", "Guadalajara", "México", "MX", "LA", 20.52, -103.31),
    ("SJD", "Los Cabos", "México", "MX", "LA", 23.15, -109.72),
    ("PVR", "Puerto Vallarta", "México", "MX", "LA", 20.68, -105.25),
    ("MID", "Mérida", "México", "MX", "LA", 20.94, -89.66),
    ("OAX", "Oaxaca", "México", "MX", "LA", 16.99, -96.73),
    ("GUA", "Ciudad de Guatemala", "Guatemala", "GT", "LA", 14.58, -90.53),
    ("FRS", "Flores (Tikal)", "Guatemala", "GT", "LA", 16.91, -89.87),
    ("BZE", "Belice", "Belice", "BZ", "LA", 17.54, -88.31),
    ("SAP", "San Pedro Sula", "Honduras", "HN", "LA", 15.45, -87.92),
    ("TGU", "Tegucigalpa", "Honduras", "HN", "LA", 14.06, -87.22),
    ("RTB", "Roatán", "Honduras", "HN", "LA", 16.32, -86.52),
    ("SAL", "San Salvador", "El Salvador", "SV", "LA", 13.44, -89.06),
    ("MGA", "Managua", "Nicaragua", "NI", "LA", 12.14, -86.17),
    ("LIR", "Liberia (Guanacaste)", "Costa Rica", "CR", "LA", 10.59, -85.54),
    ("MBJ", "Montego Bay", "Jamaica", "JM", "LA", 18.50, -77.91),
    ("KIN", "Kingston", "Jamaica", "JM", "LA", 17.94, -76.79),
    ("PAP", "Puerto Príncipe", "Haití", "HT", "LA", 18.58, -72.29),
    ("NAS", "Nasáu", "Bahamas", "BS", "LA", 25.04, -77.47),
    ("BGI", "Bridgetown", "Barbados", "BB", "LA", 13.07, -59.49),
    ("POS", "Puerto España", "Trinidad y Tobago", "TT", "LA", 10.60, -61.34),
    ("UVF", "Santa Lucía", "Santa Lucía", "LC", "LA", 13.73, -60.95),
    ("GND", "Granada", "Granada", "GD", "LA", 12.00, -61.79),
    ("SVD", "San Vicente", "San Vicente y las Granadinas", "VC", "LA", 13.16, -61.15),
    ("ANU", "Antigua", "Antigua y Barbuda", "AG", "LA", 17.14, -61.79),
    ("SKB", "San Cristóbal", "San Cristóbal y Nieves", "KN", "LA", 17.31, -62.72),
    ("DOM", "Dominica", "Dominica", "DM", "LA", 15.55, -61.30),
    ("AUA", "Aruba", "Países Bajos (Aruba)", "AW", "LA", 12.50, -70.02),
    ("CUR", "Curazao", "Países Bajos (Curazao)", "CW", "LA", 12.19, -68.96),
    ("PTP", "Guadalupe", "Francia (Guadalupe)", "GP", "LA", 16.27, -61.53),
    ("FDF", "Martinica", "Francia (Martinica)", "MQ", "LA", 14.59, -61.00),
    ("VRA", "Varadero", "Cuba", "CU", "LA", 23.03, -81.44),
    ("POP", "Puerto Plata", "Rep. Dominicana", "DO", "LA", 19.76, -70.57),
    ("GEO", "Georgetown", "Guyana", "GY", "LA", 6.50, -58.25),
    ("PBM", "Paramaribo", "Surinam", "SR", "LA", 5.45, -55.19),
    ("VVI", "Santa Cruz de la Sierra", "Bolivia", "BO", "LA", -17.64, -63.14),
    ("LPB", "La Paz", "Bolivia", "BO", "LA", -16.51, -68.19),
    ("ASU", "Asunción", "Paraguay", "PY", "LA", -25.24, -57.52),
    ("SSA", "Salvador de Bahía", "Brasil", "BR", "LA", -12.91, -38.33),
    ("REC", "Recife", "Brasil", "BR", "LA", -8.13, -34.92),
    ("FOR", "Fortaleza", "Brasil", "BR", "LA", -3.78, -38.53),
    ("FLN", "Florianópolis", "Brasil", "BR", "LA", -27.67, -48.55),
    ("BSB", "Brasilia", "Brasil", "BR", "LA", -15.87, -47.92),
    ("IGU", "Foz do Iguaçu", "Brasil", "BR", "LA", -25.60, -54.49),
    ("BRC", "Bariloche", "Argentina", "AR", "LA", -41.15, -71.16),
    ("MDZ", "Mendoza", "Argentina", "AR", "LA", -32.83, -68.79),
    ("IGR", "Puerto Iguazú", "Argentina", "AR", "LA", -25.74, -54.47),
    ("USH", "Ushuaia", "Argentina", "AR", "LA", -54.84, -68.30),
    ("FTE", "El Calafate", "Argentina", "AR", "LA", -50.28, -72.05),
    ("PUQ", "Punta Arenas", "Chile", "CL", "LA", -53.00, -70.85),
    ("IPC", "Isla de Pascua", "Chile", "CL", "LA", -27.16, -109.42),
    ("AQP", "Arequipa", "Perú", "PE", "LA", -16.34, -71.58),
    ("GYE", "Guayaquil", "Ecuador", "EC", "LA", -2.16, -79.88),
    ("GPS", "Galápagos", "Ecuador", "EC", "LA", -0.45, -90.27),
    ("CLO", "Cali", "Colombia", "CO", "LA", 3.54, -76.38),
    ("ADZ", "San Andrés", "Colombia", "CO", "LA", 12.58, -81.71),
    ("PMV", "Isla Margarita", "Venezuela", "VE", "LA", 10.91, -63.97),
    ("PDP", "Punta del Este", "Uruguay", "UY", "LA", -34.86, -55.09),
]

# Países sin aeropuerto comercial propio -> aeropuerto más práctico
NEARBY = {
    "AD": ("Andorra", "BCN", "EU"),
    "MC": ("Mónaco", "NCE", "EU"),
    "LI": ("Liechtenstein", "ZRH", "EU"),
    "SM": ("San Marino", "BLQ", "EU"),
    "VA": ("Ciudad del Vaticano", "ROM", "EU"),
    "PS": ("Palestina", "AMM", "ME"),
}

# Nombre en español de los 195 países (ISO 3166-1 alfa-2)
COUNTRY_NAMES = {
    "AF": "Afganistán", "AL": "Albania", "DE": "Alemania", "AD": "Andorra", "AO": "Angola", "AG": "Antigua y Barbuda",
    "SA": "Arabia Saudí", "DZ": "Argelia", "AR": "Argentina", "AM": "Armenia", "AU": "Australia", "AT": "Austria",
    "AZ": "Azerbaiyán", "BS": "Bahamas", "BD": "Bangladés", "BB": "Barbados", "BH": "Baréin", "BE": "Bélgica",
    "BZ": "Belice", "BJ": "Benín", "BY": "Bielorrusia", "MM": "Myanmar", "BO": "Bolivia", "BA": "Bosnia y Herzegovina",
    "BW": "Botsuana", "BR": "Brasil", "BN": "Brunéi", "BG": "Bulgaria", "BF": "Burkina Faso", "BI": "Burundi",
    "BT": "Bután", "CV": "Cabo Verde", "KH": "Camboya", "CM": "Camerún", "CA": "Canadá", "QA": "Catar", "TD": "Chad",
    "CL": "Chile", "CN": "China", "CY": "Chipre", "VA": "Ciudad del Vaticano", "CO": "Colombia", "KM": "Comoras",
    "KP": "Corea del Norte", "KR": "Corea del Sur", "CI": "Costa de Marfil", "CR": "Costa Rica", "HR": "Croacia",
    "CU": "Cuba", "DK": "Dinamarca", "DM": "Dominica", "EC": "Ecuador", "EG": "Egipto", "SV": "El Salvador",
    "AE": "Emiratos Árabes", "ER": "Eritrea", "SK": "Eslovaquia", "SI": "Eslovenia", "ES": "España",
    "US": "Estados Unidos", "EE": "Estonia", "SZ": "Esuatini", "ET": "Etiopía", "PH": "Filipinas", "FI": "Finlandia",
    "FJ": "Fiyi", "FR": "Francia", "GA": "Gabón", "GM": "Gambia", "GE": "Georgia", "GH": "Ghana", "GD": "Granada",
    "GR": "Grecia", "GT": "Guatemala", "GN": "Guinea", "GQ": "Guinea Ecuatorial", "GW": "Guinea-Bisáu", "GY": "Guyana",
    "HT": "Haití", "HN": "Honduras", "HU": "Hungría", "IN": "India", "ID": "Indonesia", "IQ": "Irak", "IR": "Irán",
    "IE": "Irlanda", "IS": "Islandia", "MH": "Islas Marshall", "SB": "Islas Salomón", "IL": "Israel", "IT": "Italia",
    "JM": "Jamaica", "JP": "Japón", "JO": "Jordania", "KZ": "Kazajistán", "KE": "Kenia", "KG": "Kirguistán",
    "KI": "Kiribati", "KW": "Kuwait", "LA": "Laos", "LS": "Lesoto", "LV": "Letonia", "LB": "Líbano", "LR": "Liberia",
    "LY": "Libia", "LI": "Liechtenstein", "LT": "Lituania", "LU": "Luxemburgo", "MK": "Macedonia del Norte",
    "MG": "Madagascar", "MY": "Malasia", "MW": "Malaui", "MV": "Maldivas", "ML": "Malí", "MT": "Malta",
    "MA": "Marruecos", "MU": "Mauricio", "MR": "Mauritania", "MX": "México", "FM": "Micronesia", "MD": "Moldavia",
    "MC": "Mónaco", "MN": "Mongolia", "ME": "Montenegro", "MZ": "Mozambique", "NA": "Namibia", "NR": "Nauru",
    "NP": "Nepal", "NI": "Nicaragua", "NE": "Níger", "NG": "Nigeria", "NO": "Noruega", "NZ": "Nueva Zelanda",
    "OM": "Omán", "NL": "Países Bajos", "PK": "Pakistán", "PW": "Palaos", "PS": "Palestina", "PA": "Panamá",
    "PG": "Papúa Nueva Guinea", "PY": "Paraguay", "PE": "Perú", "PL": "Polonia", "PT": "Portugal",
    "GB": "Reino Unido", "CF": "Rep. Centroafricana", "CZ": "Chequia", "CG": "Congo", "CD": "R. D. del Congo",
    "DO": "Rep. Dominicana", "RW": "Ruanda", "RO": "Rumanía", "RU": "Rusia", "WS": "Samoa",
    "KN": "San Cristóbal y Nieves", "SM": "San Marino", "VC": "San Vicente y las Granadinas", "LC": "Santa Lucía",
    "ST": "Santo Tomé y Príncipe", "SN": "Senegal", "RS": "Serbia", "SC": "Seychelles", "SL": "Sierra Leona",
    "SG": "Singapur", "SY": "Siria", "SO": "Somalia", "LK": "Sri Lanka", "ZA": "Sudáfrica", "SD": "Sudán",
    "SS": "Sudán del Sur", "SE": "Suecia", "CH": "Suiza", "SR": "Surinam", "TH": "Tailandia", "TZ": "Tanzania",
    "TJ": "Tayikistán", "TL": "Timor Oriental", "TG": "Togo", "TO": "Tonga", "TT": "Trinidad y Tobago", "TN": "Túnez",
    "TM": "Turkmenistán", "TR": "Turquía", "TV": "Tuvalu", "UA": "Ucrania", "UG": "Uganda", "UY": "Uruguay",
    "UZ": "Uzbekistán", "VU": "Vanuatu", "VE": "Venezuela", "VN": "Vietnam", "YE": "Yemen", "DJ": "Yibuti",
    "ZM": "Zambia", "ZW": "Zimbabue",
}
